In [1]:
l=range(1000000)

In [2]:
import numpy as np

In [3]:
#ARANGE list kay range jesa hi kam karta hy range list create karay ga aur ARANGE ka fuction array return karay ga 

In [4]:
d = np.arange(1000000)

In [5]:
%time for i in range(1,10): r=[x*2 for x in l]

Wall time: 1.38 s


In [6]:
%time for i in range(1,10): r=d*2 #100 times faster

Wall time: 46 ms


In [8]:
x = np.zeros((4,4))
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
x = np.ones((4,4))
x

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.empty((7,7))

array([[1.06883936e-311, 1.06880249e-311, 1.06880249e-311,
        1.06883941e-311, 1.06883940e-311, 1.06883902e-311,
        1.06883936e-311],
       [1.06883940e-311, 1.06880249e-311, 1.06880249e-311,
        1.06883936e-311, 1.06883940e-311, 1.06880249e-311,
        1.06883941e-311],
       [1.06883940e-311, 1.06880249e-311, 1.06883936e-311,
        1.06883936e-311, 1.06883936e-311, 1.06883940e-311,
        1.06880249e-311],
       [1.06880249e-311, 1.06883938e-311, 1.06883941e-311,
        1.06883940e-311, 1.06883934e-311, 1.06883940e-311,
        1.06880249e-311],
       [1.06880249e-311, 1.06883941e-311, 1.06883941e-311,
        1.06880249e-311, 1.06883941e-311, 1.06883940e-311,
        1.06883940e-311],
       [1.06883941e-311, 1.06883940e-311, 1.06883941e-311,
        1.06880249e-311, 1.06883941e-311, 1.06883936e-311,
        1.06883936e-311],
       [1.06883941e-311, 1.06883936e-311, 1.06880249e-311,
        1.06883941e-311, 1.06883936e-311, 1.06883941e-311,
        1.06883940

In [14]:
l = [1,4,3,4]

In [15]:
np.array(l)

array([1, 4, 3, 4])

In [25]:
z=np.arange(1,100,10)

In [26]:
z.shape

(10,)

In [28]:
x=np.zeros((10,10))

In [30]:
y=x.reshape((2,2,5,5))
y

array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]])

In [31]:
y.dtype

dtype('float64')

In [32]:
y.ndim

4

In [34]:
a = np.random.rand(10)

In [35]:
b = np.random.rand(10)

In [36]:
a

array([0.14930771, 0.9753213 , 0.92678372, 0.15222163, 0.76161022,
       0.64718357, 0.60103477, 0.63866896, 0.15403082, 0.21559097])

In [37]:
b

array([0.91627394, 0.69353581, 0.84374909, 0.37593949, 0.60694228,
       0.38549769, 0.3103425 , 0.1268136 , 0.94579431, 0.86358097])

In [38]:
a+b #this is not applicable in lists but in numpy

array([1.06558165, 1.6688571 , 1.77053281, 0.52816112, 1.3685525 ,
       1.03268127, 0.91137727, 0.76548255, 1.09982513, 1.07917194])

In [39]:
a-b

array([-0.76696622,  0.28178549,  0.08303464, -0.22371786,  0.15466794,
        0.26168588,  0.29069228,  0.51185536, -0.7917635 , -0.64799   ])

In [44]:
2*(a*b)

array([0.27361353, 1.35284048, 1.56394584, 0.11445224, 0.92450688,
       0.49897555, 0.37305326, 0.16198381, 0.29136294, 0.37236052])

In [41]:
a/b

array([0.16295096, 1.40630273, 1.09841153, 0.40490992, 1.25483139,
       1.67882606, 1.93668215, 5.03628145, 0.16285868, 0.24964766])

In [45]:
a>0

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])